language: node_js

node_js:
  - '10'

install:
  - npm install

script:
  - npm test
  - npm run eslint
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: koenkanters94@gmail.com
  api_key:
    secure: oo4HaoS6waWEtwykkdDdbWWQPazwrhZn46PiyagVjKUtJQgdgEDo3v0YrWiPR+/rp/VNnx6rCIq4P5g0dk795EqWRYyRfNqj1v9WWjrH6iZgI4k2VgwZx9qUC1nMTgX6u6ImohPXdjXI2aV5+uh9vGdowcMIi1MCIE5w9wJmXt/VtAMTFqOHwqP/d91F8PUURmemzqnI1bau/ctVsieCssRfsq76if2It8cntfjI2V6Z8c5d4M5BY6F/jjCvDtxv0zOQl+9M0PZZoh4Va+2lBfjU1aJ0iJHrFhVwpzArDnujGDXU6GdNCWQcBz3+pG9FGmnD6/X6rpWg5gJ0cNLewuXYLQ9AD3gW0uzG+fAlet4ADhD1AShQIyMf+gK74a1uwerEt1UgpyYOwkHnS21Q4wlN5ZXZGB9iSAU7blvqdiXst6e8EJImwIXjTJ8yFFgzDdcc2hoKNcZb6nBhpAetVYWvdJcjyRaIQr9Zzk40KWThwfFS/mmpbkpcypzOkrCXvYMJB3QtOPF2b/uD/DYyFFw3bcsJPKbtJ8Zj3/lw1zFZIg0aoiwozVuX5H9WSZQsws6ixkFenr2WlU+T0t16psBUAzzHe7l6ZADjzL/hpwHHCsmLSMCpTHqMyoANSZcv7nactRBmQW45wXQB4dXKlMX7z3qb9DJ+J6bOy1GBrng=
  on:
    tags: true
    branch: master